### ISSUE TITLE
Trouble adding SNMP exporter

### ISSUE THREAD

**Issue by jmreicha** [carlosedp/prometheus-operator-ARM#2]
Thanks for your work on this.  I am trying to get the SNMP exporter working and have used your configurations as a starting place but I am having trouble with the `ServiceMonitor` and I'm not sure how to troubleshoot it.

I can see the snmp related servicemonitor object in Kubernetes after creating it with,

```
kubectl get servicemonitor -n monitoring -o yaml | grep snmp
```

But I don't see any of the configuration anywhere else in Prometheus.  Likewise none of the SNMP metrics are showing up in Grafana.  Nothing is really showing up the prometheus-operator logs either about the configuration.

I have tested that the exporter is working and I can get to it and scrape a target manually.

Any thoughts or insights?  Maybe I am missing something simple?  I can post any other details if needed.

**Comment by carlosedp** [comment]
My deployment was pretty straightforward, I created the service, the deployment and the servicemonitor with the manifests/snmp-exporter files. They must be created all in the same namespace (together with Prometheus). On the manifests I didn't add the namespace but you can do the kubectl apply -n [namespace] -f [file] like you did.

You just need to adjust in the ServiceMonitor, the target IP and SNMP module you are using:
```
...
endpoints:
  - interval: 60s
    port: http-metrics
    params:
      module:
      - ddwrt
      target:
      - 192.168.1.1
    path: "/snmp"
    targetPort: 9116
...
```

It was displayed on Prometheus targets:

![image](https://user-images.githubusercontent.com/20382/38060140-0ffd51b2-32af-11e8-9953-7c346954b6c0.png)

Hope I can help.. logs doesn't contain any info about loading this.

**Comment by jmreicha** [comment]
Huh, that's pretty much what I did. I will double check to see if the endpoint shows up in the Prometheus targets but I'm not seeing the configuration for it.

Did you have to do anything special by adding a `Prometheus` object or anything with secrets?

**Comment by carlosedp** [comment]
In the first time, I tried to deploy like some guys mentioned on the issue, creating the secret. But I deleted it since the config was made into the ServiceMonitor itself.

**Comment by jmreicha** [comment]
The operator seems to just not be picking up the configuration for some reason 😕 Here's what my `ServiceMonitor` definition looks like.

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: snmp-exporter
  name: snmp-exporter
spec:
  jobLabel: k8s-app
  selector:
    app: snmp-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - interval: 60s
    port: http-metrics
    params:
      module:
      - default
      target:
      - 1.2.3.4
    path: "/snmp"
    targetPort: 9116
```

I'm using a custom image with the `default` module.  As far as I can tell names and labels and everything else match up.
